matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8